SET SQLBLANKLINES ON
CREATE TABLE TB_PESSOA
(
  CODIGO_PESSOA NUMBER(9) NOT NULL
, NOME VARCHAR(256) NOT NULL
, SOBRENOME VARCHAR2(256) NOT NULL
, IDADE NUMBER(3) NOT NULL
, LOGIN VARCHAR2(50) NOT NULL
, SENHA VARCHAR2(50) NOT NULL
, STATUS NUMBER(3) NOT NULL
, CONSTRAINT TB_PESSOA_PK PRIMARY KEY
  (
    CODIGO_PESSOA
  )
  ENABLE
);

CREATE TABLE TB_UF
(
  CODIGO_UF NUMBER(9) NOT NULL
, SIGLA VARCHAR2(3) NOT NULL
, NOME VARCHAR2(60) NOT NULL
, STATUS NUMBER(3) NOT NULL
, CONSTRAINT TB_UF_PK PRIMARY KEY
  (
    CODIGO_UF
  )
  ENABLE
);

CREATE TABLE TB_MUNICIPIO
(
  CODIGO_MUNICIPIO NUMBER(9) NOT NULL
, CODIGO_UF NUMBER(9) NOT NULL
, NOME VARCHAR2(256)
, STATUS NUMBER(3)
, CONSTRAINT TB_MUNICIPIO_PK PRIMARY KEY
  (
    CODIGO_MUNICIPIO
  )
  ENABLE
);

CREATE TABLE TB_BAIRRO
(
  CODIGO_BAIRRO NUMBER(9) NOT NULL
, CODIGO_MUNICIPIO NUMBER(9) NOT NULL
, NOME VARCHAR2(256) NOT NULL
, STATUS NUMBER(3)
, CONSTRAINT TB_BAIRRO_PK PRIMARY KEY
  (
    CODIGO_BAIRRO
  )
  ENABLE
);

CREATE TABLE TB_ENDERECO
(
  CODIGO_ENDERECO NUMBER(9) NOT NULL
, CODIGO_PESSOA NUMBER(9) NOT NULL
, CODIGO_BAIRRO NUMBER(9) NOT NULL
, NOME_RUA VARCHAR2(256) NOT NULL
, NUMERO VARCHAR2(10) NOT NULL
, COMPLEMENTO VARCHAR2(20)
, CEP VARCHAR2(10) NOT NULL
, CONSTRAINT TB_ENDERECO_PK PRIMARY KEY
  (
    CODIGO_ENDERECO
  )
  ENABLE
);

ALTER TABLE TB_BAIRRO
ADD CONSTRAINT TB_BAIRRO_FK1 FOREIGN KEY
(
  CODIGO_MUNICIPIO
)
REFERENCES TB_MUNICIPIO
(
  CODIGO_MUNICIPIO
)
ENABLE;

ALTER TABLE TB_ENDERECO
ADD CONSTRAINT TB_ENDERECO_FK1 FOREIGN KEY
(
  CODIGO_PESSOA
)
REFERENCES TB_PESSOA
(
  CODIGO_PESSOA
)
ENABLE;

ALTER TABLE TB_ENDERECO
ADD CONSTRAINT TB_ENDERECO_FK2 FOREIGN KEY
(
  CODIGO_BAIRRO
)
REFERENCES TB_BAIRRO
(
  CODIGO_BAIRRO
)
ENABLE;

ALTER TABLE TB_MUNICIPIO
ADD CONSTRAINT TB_MUNICIPIO_FK1 FOREIGN KEY
(
  CODIGO_UF
)
REFERENCES TB_UF
(
  CODIGO_UF
)
ENABLE;

COMMENT ON COLUMN TB_UF.STATUS IS '1 - ATIVADO
2 - DESATIVADO';

COMMENT ON COLUMN TB_MUNICIPIO.STATUS IS '1 - ATIVADO
2 - DESATIVADO';

COMMENT ON COLUMN TB_BAIRRO.STATUS IS '1- ATIVADO
2- DESATIVADO';

COMMENT ON COLUMN TB_PESSOA.STATUS IS '1 - ATIVADO
2 - DESATIVADO';


CREATE SEQUENCE SEQUENCE_PESSOA INCREMENT BY 1 START WITH 1 MAXVALUE 999999999 MINVALUE 1 NOCACHE;
CREATE SEQUENCE SEQUENCE_ENDERECO INCREMENT BY 1 START WITH 1 MAXVALUE 999999999 MINVALUE 1 NOCACHE;
CREATE SEQUENCE SEQUENCE_BAIRRO INCREMENT BY 1 START WITH 1 MAXVALUE 999999999 MINVALUE 1 NOCACHE;
CREATE SEQUENCE SEQUENCE_MUNICIPIO INCREMENT BY 1 START WITH 1 MAXVALUE 999999999 MINVALUE 1 NOCACHE;
CREATE SEQUENCE SEQUENCE_UF INCREMENT BY 1 START WITH 1 MAXVALUE 999999999 MINVALUE 1 NOCACHE;